version: '3.9'
services:
  node:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    tty: true
    volumes:
      - ./:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "cd /usr/src/app/src && npm run dev"
    ports:
      - "3000:3000"